### ISSUE TITLE
Allow base nodes and wallets to use cookie auth with tor control port 

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#2808]
Comms' tor client already supports cookie auth however the node configs do not. 

Example config
```toml
# Give cookie
tor_control_auth = "cookie=a62fb72c23...." 
# Read from a cookie file
tor_control_auth = "cookie=@/path/to/cookie" 
```

Considerations:
1. Could the file path be omitted which then uses a default standard path?
2.  Behaviour if the cookie cannot be found 
      - warning message, then fallback
      - exit with config error  
4. Is support for safecookies needed?
