### ISSUE TITLE
wallet should configure itself to speak the p2p protocol locally if local base node detected

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#4417]
related to #4414 but for p2p

Comms is able to communicate directly for some peers if configured before initialization.
We may have to add the ability to configure this post-initialization.

Pertinent configuration items:

```toml
[wallet.p2p]
proxy_bypass_for_outbound_tcp = true
bypass_proxy_addresses = ["/ip4/127.0.0.1/tcp/xxxx"] 
```
