### ISSUE TITLE
docker version "Exec format" error on raspberry pi 5

### ISSUE THREAD

**Issue by S0litaire** [tari-project/tari#7142]
I'm trying to run the docker version of the node ion my Rpi5 4gb version.

1. create docker.compose.yaml
2. start docker compose file
3. docker app keeps restarting

Here is the docker-compose.yaml I am using:
```                                                                                               
services:
  minotari_node:
    image: quay.io/tarilabs/minotari_node:latest-nextnet
    restart: unless-stopped
    volumes:
      - ./data:/root/.tari
# These 2 params are required for an interactive docker-compose session
    stdin_open: true
    tty: true
    expose:
      - 18142
    ports:
      - "18142:18142"
```
Docker log output : 
```
Starting node with following docker environment:
executable: minotari_node
WAIT_FOR_TOR: 0
base folder (in container): /var/tari/node
config file (in container): /var/tari/config/config.toml
arguments (in container): --non-interactive-mode
arguments count (in container): 1
Starting node ...
 > command: minotari_node --config /var/tari/config/config.toml --base-path /var/tari/node --non-interactive-mode <
/usr/local/bin/start_tari_app.sh: line 39: /usr/local/bin/minotari_node: cannot execute binary file: Exec format error
/usr/local/bin/start_tari_app.sh: line 39: /usr/local/bin/minotari_node: Success
```
Rpi5 4Gb version
OS : Ubuntu 25.10 server
